Remove flow typing from main branch
abeln/dotty pull request #43
Opened 2019-11-08 20:47 UTC by noti0na1

2019-11-08 20:57 UTC, abeln requested changes
Thanks for doing this! I found a few instances where we still referenced flow typing material, so those need to be removed.

2019-11-08 20:57 UTC, abeln commented on compiler/src/dotty/tools/dotc/core/Types.scala
> +  final class NonNullTermRef(prefix: Type, designator: Designator) extends TermRef(prefix, designator) {
This should go in the flow typing PR.

2019-11-08 20:57 UTC, abeln commented on docs/docs/internals/explicit-nulls.md
> +  4. a module for "flow typing", so we can work more naturally with nullable values
Let's remove this.

2019-11-08 20:57 UTC, abeln commented on docs/docs/internals/explicit-nulls.md
> +Flow Typing
Let's remove this section.

2019-11-08 20:57 UTC, abeln commented on docs/docs/internals/explicit-nulls.md
> +#### NonNullTermRef
Remove

2019-11-08 20:57 UTC, abeln commented on docs/docs/internals/explicit-nulls.md
> +#### ValDefInBlockCompleter
Remove

2019-11-08 20:57 UTC, abeln commented on docs/docs/reference/other-new-features/explicit-nulls.md
> +## Flow Typing
Remove

2019-11-08 22:04 UTC, noti0na1 commented
@abeln Removed

2019-11-12 19:41 UTC, abeln approved these changes

2019-11-12 19:41 UTC, merged